Task 4: Extend API
itc1205/StockHouse pull request #11
Opened 2024-05-09 19:59 UTC by itc1205

2024-05-11 09:46 UTC, GUR-ok requested changes

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/configurations/property/ServiceProperties.java
> +public class ServiceProperties {
Почему это в этом мре?

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/configurations/property/RestProperties.java
> +public class RestProperties {
Почему это в этом мре?

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/controller/CustomerController.java
> +
лишние строки

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/controller/OrderController.java
> +        CustomerDTO customerDTO = customerService.getCustomer(customerId);
Почему логика в контроллере? все вынести в сервис!

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/model/OrderEntity.java
> +    @OneToMany(mappedBy = "order", cascade = CascadeType.PERSIST)
зачем каскадность законфижена? чем дефолтная не устраивает?

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/model/OrderEntity.java
> +    @JoinColumn(name = "customer_id", nullable = false)
За счет чего решается проблема n+1 с customer?
Мб поставим     @Fetch(FetchMode.JOIN) ?

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/model/OrderedProductEntity.java
> +    BigDecimal price;
почему не private?

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/model/OrderedProductEntity.java
> +    Integer quantity;
почему не private?

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/model/OrderedProductEntity.java
> +@EqualsAndHashCode
@EqualsAndHashCode убрать и определить вручную

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/exceptions/order/OrderNotFoundException.java
> +public class OrderNotFoundException extends Throwable {
Наследовать от RuntimeException. Тогда не придется обрабатывать как checked и захламлять сигнатуры методов. Сделать для всех кастомных исключений

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/service/order/OrderService.java
> +    OrderDTO getOrderById(CustomerDTO customer, UUID id) throws OrderNotFoundException, InsufficientRightsException;
throws InsufficientProductsException, ProductNotFoundException, CustomerNotFoundException; - это жесть. так не надо. наследуй исключения от RuntimeException и тут это убрать.

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/service/order/OrderServiceImpl.java
> +            throw new InsufficientRightsException();
InsufficientRightsException - не оч нравится ( AccessDeniedException давай.

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/service/order/OrderServiceImpl.java
> +
по неск.пустых строк не оставляем

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/service/order/OrderServiceImpl.java
> +
тут тоже неск пустых строк

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/service/order/OrderServiceImpl.java
> +        OrderEntity order = orderRepository.findById(id).orElseThrow(OrderNotFoundException::new);
Как тут решается n+1? Скинь сюда скрин с запросами хибернейт в этот момент

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/service/order/OrderServiceImpl.java
> +    public UUID createOrder(CustomerDTO customer, OrderDTO order) throws InsufficientProductsException, ProductNotFoundException, CustomerNotFoundException {
order переименуй в request или createOrderRequest. по коду не понятно что это за ордер такой

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/service/order/OrderServiceImpl.java
> +    public UUID createOrder(CustomerDTO customer, OrderDTO order) throws InsufficientProductsException, ProductNotFoundException, CustomerNotFoundException {
убрать исключения из сигнатуры. грязно

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/service/order/OrderServiceImpl.java
> +        OrderEntity finalNewOrder = newOrder;
OrderEntity finalNewOrder =  newOrder; - так не надо. есть же уже ссылка на ордер.

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/repository/ProductRepository.java
> +    Stream<ProductEntity> streamAllByIds(Set<UUID>ids);
форматирование. нет пробела перед ids

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/service/order/OrderServiceImpl.java
> +        List<ProductDTO> products = orderedProductRepository.findByOrderId(id);
где orderedProductRepository в МР? он потерялся и не закоммитился.

2024-05-11 09:46 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/service/order/OrderServiceImpl.java
> +        List<OrderedProductEntity> orderedProductEntities = productRepository.streamAllByIds(requestProducts.keySet()).map(
ну я бы не делал streamAllByIds.. просто бы список вернул и потом сделал из него стрим. Кажется что список универсальней, если будут другие методы этим пользоваться.. ну хз. можно так оставить.

2024-05-15 20:09 UTC, itc1205 commented on src/main/java/com/itc/StockHouse/service/order/OrderServiceImpl.java
> +        OrderEntity order = orderRepository.findById(id).orElseThrow(OrderNotFoundException::new);
![image](https://github.com/itc1205/StockHouse/assets/85411555/cb431d49-832b-47c8-8a55-c234344d61ff)

2024-05-15 20:40 UTC, itc1205 commented
Пофиксил МР + потерянная фотка ER-Диаграммы из DBeaver
![image](https://github.com/itc1205/StockHouse/assets/85411555/6c559846-1719-4f0b-9087-a84f6fe58fb8)

2024-05-23 05:58 UTC, GUR-ok approved these changes
Давай подмержим

2024-05-29 10:10 UTC, merged