Task2: Add criteria search
itc1205/StockHouse pull request #4
Opened 2024-04-25 16:59 UTC by itc1205

2024-04-26 08:50 UTC, GUR-ok requested changes

2024-04-26 08:50 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/controller/SearchController.java
> +import org.springframework.web.bind.annotation.*;
схлопнутых импортов избегаем

2024-04-26 08:50 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/controller/SearchController.java
> +            Integer page,
давай не page и size отдельно, а чтобы прям Pageable сразу тут контроллером принималось (там еще sort добавится)

2024-04-26 08:50 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/dto/CriteriaDTO.java
> +    private final PredicateMapperStrategy<T> predicateMapperStrategy;
мб поле predicateMapperStrategy сделаем статическим? тогда не нужно будет создавать каждый раз объект стратегии для нового объекта критерия

2024-04-26 08:50 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/dto/CriteriaDTO.java
> +public class CriteriaDTO<T> {
сделай интерфейсом, и метод getStrategy, тогда стратегию получится записать в статик поле в каждой реализации

2024-04-26 08:50 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/dto/CriteriaDTO.java
> +    public <X> Predicate toPredicate(CriteriaBuilder criteriaBuilder, Root<X> root) {
Давай стараться не нарушать принцип единой ответственности. Формирования предикатов тут быть не должно. Пусть за это отвечает отдельный класс. Например public class ProductSpecification implements Specification<ProductEntity>, который хранит в себе список всех критериев и собирает предикаты.

2024-04-26 08:50 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/dto/OperationDTO.java
> +    EQUAL(Arrays.asList("=", "EQUAL")),
Arrays.asList("=", "EQUAL") - у тебя EQUAL есть в самом названии енума

2024-04-26 08:50 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/dto/OperationDTO.java
> +    EQUAL(Arrays.asList("=", "EQUAL")),
```
package com.crudshop.demo.service.search.enums;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum OperationType {

    EQUAL("="),
    GRATER_THAN_OR_EQ(">="),
    LESS_THAN_OR_EQ("<="),
    LIKE("~");

    private final String code;

    OperationType(String code) {
        this.code = code;
    }

    @JsonValue
    public String getCode() {
        return code;
    }

    @JsonCreator
    public static OperationType fromCode(String code) {
        for (OperationType operationType : OperationType.values()) {
            if (operationType.name().equals(code) || operationType.code.equals(code)) {
                return operationType;
            }
        } return null;
    }
}
```

2024-04-26 08:50 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/dto/CriteriaDTO.java
> +    public <X> Predicate toPredicate(CriteriaBuilder criteriaBuilder, Root<X> root) {
или у тебя для этого уже есть public class CriteriaMapper.. который сейчас толком ниче не делает

2024-04-26 08:52 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/controller/SearchController.java
> +            List<CriteriaDTO<?>> criteriaList,
Работу валидаций проверял? кажется не будет работать

2024-05-04 09:36 UTC, GUR-ok commented
конфликты

2024-05-06 19:52 UTC, itc1205 commented
Отменил форс-пушем мердж который внес старые изменения

2024-05-11 09:20 UTC, GUR-ok approved these changes
делай мерж со сквошем

2024-05-14 19:42 UTC, merged