Task 3: Add currency handling
itc1205/StockHouse pull request #6
Opened 2024-05-02 10:11 UTC by itc1205

2024-05-04 09:49 UTC, GUR-ok requested changes

2024-05-04 09:49 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/configurations/WebClientConfiguration.java
> +        return WebClient.create();
давай тут хост currencyservice сразу зашьем в бин вебклиента

2024-05-04 09:49 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/client/currency/CurrencyServiceClientImpl.java
> +@ConditionalOnExpression(value = "#{'${currency-service.mode:none}'.equals('base')}")
убрать тут @ConditionalOnProperty а на моке поставить primary

2024-05-04 09:49 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/client/currency/CurrencyServiceClientMock.java
> +@ConditionalOnExpression(value = "#{'${currency-service.mode:none}'.equals('mock')}")
тут добавить primary и активацию по @ConditionalOnProperty(name = "rest.currency-service.mock.enabled:false")

2024-05-04 09:49 UTC, GUR-ok commented on src/main/resources/application.yaml
> +currency-service:
```
rest:
   currency-service:
      host:
      methods: ...
      mock:
         enabled: true
```

2024-05-04 09:49 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/client/currency/CurrencyServiceClientImpl.java
> +    @Value("${currency-service.methods.get-currency}")
Давай больше не будем инжектить через value.
Создай класс для пропертей для rest взаимодействия
@ConfigurationProperties

2024-05-04 09:49 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/client/currency/CurrencyServiceClientImpl.java
> +    @Value("${currency-service.host}")
это уйдет в создание бина вебклиента

2024-05-04 09:49 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/client/currency/CurrencyServiceClientImpl.java
> +    public HashMap<String, BigDecimal> retrieveCurrencies() {
почему мапа в ответе? сделай нормальный класс

2024-05-04 09:49 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/controller/StockController.java
> +    @Autowired
инжект через конструктор

2024-05-04 09:49 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/support/currency/CurrencyProvider.java
> +public class CurrencyProvider {
Давай это будет наз-ся ExchangeRateProvider

2024-05-04 09:49 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/support/currency/CurrencySessionBean.java
> +public class CurrencySessionBean {
А это будет наз-ся  CurrencyProvider

2024-05-04 09:49 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/support/currency/CurrencySessionBean.java
> +    private String currencyName;
Валюту сделать енумом. и тут задать дефолтно руб

2024-05-04 09:49 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/utils/CurrencyInputStreamMappingUtil.java
> +public class CurrencyInputStreamMappingUtil {
этот класс лишний

2024-05-04 09:49 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/support/currency/CurrencyRequestFilter.java
> +        if (sessionCurrency.getCurrencyName() == null) {
это условие не нужно, если дефолтно создавать CurrencySessionBean с рублем

2024-05-04 09:49 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/support/currency/CurrencyProvider.java
> +    public StockDto appendCurrency(StockDto stockDto, String currencyName) {
Не, сюда не нужно передавать внутрь и наружу дто. пусть метод принимает Currency (enum), а возвращает BigDecimal. Операцию с дто пусть делает ProductService. Вот так передавать StockDto между классами и методами и ее мутировать - не гуд

2024-05-04 09:49 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/utils/CurrencyInputStreamMappingUtil.java
> +    public HashMap<String, BigDecimal> mapFromStream(InputStream stream) throws IOException {
эту логику можно выполнить одной строчкой objectMapper.readValue(file, ExchangeRate.class); в ExchangeRateProvider (текущее название у тебя CurrencyProvider). Поэтому нет смысла выносить в отдельный метод и тем более класс.

2024-05-04 09:49 UTC, GUR-ok commented on src/main/java/com/itc/StockHouse/support/currency/CurrencyProvider.java
> +public class CurrencyProvider {
Назвал CurrencyProvider, т.е. он как бы должен выдавать валюту.. а по факту он вообще мутирует дто и валюту не выдает. Давай он будет выдавать курс BigDecimal по валюте Currency.
```
public BigDecimal getExchangeRate(Currency currency) {
    return Optional.ofNullable(getExchangeRateFromService(currency))
            .orElseGet(() -> getExchangeRateFromFile(currency));
}
```
Сделай два приватных метода. получение валюты из внешнего сервиса и получение из файла
```
private @Nullable BigDecimal getExchangeRateFromService(Currency currency) {
....
}

private BigDecimal getExchangeRateFromFile(Currency currency) {
...
}

private BigDecimal getExchangeRateByCurrency(ExchangeRate exchangeRate, Currency currency) {
   return switch (currency) {
       case USD -> exchangeRate.getExchangeRateUSD();
       case CNY -> exchangeRate.getExchangeRateCNY();
       case EUR -> exchangeRate.getExchangeRateEUR();
       case RUB -> BigDecimal.ONE;
   };
}
```

2024-05-06 20:56 UTC, itc1205 commented on src/main/java/com/itc/StockHouse/client/currency/CurrencyServiceClientImpl.java
> +    public HashMap<String, BigDecimal> retrieveCurrencies() {
Подумал что так будет проще добавить в случае чего новые валюты, дабы не трогать класс/логику обработки валют а просто добавлять дополнительное поле в JSON'чик. Переделаю на класс

2024-06-01 07:40 UTC, GUR-ok approved these changes

2024-06-06 16:17 UTC, merged